[package]
name = "sleepy-rustaceans-lang"
version = "0.1.0"
authors = ["Graham Scheaffer <me@gisch.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
